# Overlap-only Cloth5->Sport5, RS[0.8,0.1,0.1], 1 seed, unified protocol
field_separator: "\t"
data_path: "dataset"
gpu_id: 0
seed: 2022
reproducibility: True
eval_args:
  split: {"RS": [0.8, 0.1, 0.1]}
  split_valid: {"RS": [0.8, 0.2]}
  group_by: user
  order: RO
  mode: full
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: [10]
valid_metric: NDCG@10
valid_metric_bigger: True
train_epochs: ["BOTH:300"]
stopping_step: 10
source_domain:
  dataset: AmazonCloth5Ov
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating, timestamp]
  user_inter_num_interval: "[1,inf)"
  item_inter_num_interval: "[1,inf)"
target_domain:
  dataset: AmazonSport5Ov
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating, timestamp]
  user_inter_num_interval: "[1,inf)"
  item_inter_num_interval: "[1,inf)"
