field_separator: "\t"
data_path: "dataset"
gpu_id: 0
use_gpu: True
show_progress: False
seed: 2024
eval_candidate_seed: 2024
pretrained_cmf_path: "saved/CMF-Jun-07-2026_15-20-57.pth"
pretrained_cdcdr_path: "saved/CDCDR-Jun-09-2026_20-54-06.pth"
pretrained_cut_path: "saved/CUT_24-Jun-07-2026_15-21-08.pth"
pretrained_unicdr_path: "saved/UniCDR-Jun-07-2026_20-11-27.pth"
freeze_anchor: True
anchor_sampling_seed: 2024
expert_fusion_weight: 0.37
cut_fusion_weight: 0.33
unicdr_fusion_weight: 0.52
consensus_weight: 0.36

overlap_users_only: True
eval_overlap_users_only: True
seen_target_items_only: True
paired_domain_sampling: False

eval_args:
  split: {"LS": "valid_and_test"}
  split_valid: {"RS": [0.8, 0.2]}
  group_by: user
  order: TO
  mode: uni999
metrics: ["Hit", "NDCG", "Recall", "MRR"]
topk: [10]
valid_metric: NDCG@10
eval_batch_size: 8192

train_epochs: ["BOTH:30"]
train_batch_size: 1024
neg_sampling:
  uniform: 1
learning_rate: 0.001
weight_decay: 0.0
eval_step: 1
stopping_step: 5

source_domain:
  dataset: AmazonSportUniCDR
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  user_inter_num_interval: ~
  item_inter_num_interval: ~
  load_col:
    inter: [user_id, item_id, rating, timestamp]

target_domain:
  dataset: AmazonClothUniCDR
  benchmark_filename: ["train", "valid", "test"]
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  user_inter_num_interval: ~
  item_inter_num_interval: ~
  load_col:
    inter: [user_id, item_id, rating, timestamp]
