field_separator: "\t"
data_path: "dataset"
gpu_id: 1
use_gpu: True
show_progress: False
overlap_users_only: True
eval_overlap_users_only: True
seen_target_items_only: True
eval_args:
  split: {"LS": "valid_and_test"}
  split_valid: {"RS": [0.8, 0.2]}
  group_by: user
  order: TO
  mode: uni999
metrics: ["Hit", "NDCG", "Recall", "MRR"]
topk: [10]
valid_metric: NDCG@10
eval_step: 5
train_epochs: ["BOTH:100"]
paired_domain_sampling: True
warmup_epochs: 10
lr_decay: 0.9
decay_epoch: 10
stopping_step: 20

# Model hyperparams
embedding_size: 128
hidden_size: 128
n_layers: 2
dropout: 0.3
leakey: 0.1
condi_weight: 0.3
condi_non_weight: 10.0
condi_condi_weight: 10.0
isConditional: True
isCondi_norm: False
learning_rate: 0.001
train_batch_size: 1024

source_domain:
  dataset: AmazonSportUniCDR
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  user_inter_num_interval: ~
  item_inter_num_interval: ~
  load_col:
    inter: [user_id, item_id, rating, timestamp]
target_domain:
  dataset: AmazonClothUniCDR
  benchmark_filename: ["train", "valid", "test"]
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  user_inter_num_interval: ~
  item_inter_num_interval: ~
  load_col:
    inter: [user_id, item_id, rating, timestamp]
