field_separator: "\t"
data_path: "dataset"
eval_args:
  split: {"RS": [0.8, 0.1, 0.1]}
  split_valid: {"RS": [0.8, 0.2]}
  group_by: user
  order: RO
  mode: full
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: [10]
valid_metric: MRR@10
train_epochs: ["BOTH:300"]
source_domain:
  dataset: AmazonSport5
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating, timestamp]
target_domain:
  dataset: AmazonCloth5
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating, timestamp]
